title: "Heuristic model of packout applied to the 2025 Rockit™ apple fruit set"

date: 07/04/2025
date-format: long

mainfont: Geograph
monofont: Geograph
sansfont: Geograph

prefer-html: true
always_allow_html: yes
  


